<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datamodel" nsURI="http://de/opalproject/vespucci/datamodel/1.0"
    nsPrefix="de.opalproject.vespucci.datamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Ensemble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Ensemble" containment="true" resolveProxies="false" eOpposite="#//Ensemble/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Ensemble"
        eOpposite="#//Ensemble/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//EnsembleRepository"
        eOpposite="#//EnsembleRepository/contains"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintType" eType="#//ConstraintType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependencyKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="ALL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Ensemble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Ensemble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintType">
    <eLiterals name="NotAllowed"/>
    <eLiterals name="GlobalIncoming" value="1"/>
    <eLiterals name="LocalIncoming" value="2"/>
    <eLiterals name="GlobalOutgoing" value="3"/>
    <eLiterals name="LocalOutgoing" value="4"/>
    <eLiterals name="Expected" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SliceRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Slice" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnsembleRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Ensemble" containment="true" eOpposite="#//Ensemble/container"/>
  </eClassifiers>
</ecore:EPackage>
